# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - uses: actions/checkout@v4  # Клонируем репозиторий
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Указываем версию .NET
    - name: Restore dependencies
      run: dotnet restore Homeworks/UnitTests/src  # Восстанавливаем зависимости для решения
    - name: Build
      run: dotnet build --no-restore Homeworks/UnitTests/src # Строим приложение
    - name: Test
      run: dotnet test --no-build --no-restore Homeworks/UnitTests/src  # Запускаем тесты
